blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: docs.
  - name: Discussions
    url: https://github.com/lucacome/issue-test/discussions
    about: Please use discussions for general questions.
